### ISSUE TITLE
autoload crashes with elysia > 0.8.10

### ISSUE THREAD

**Issue by fredt34** [kravetsone/elysia-autoload#1]
My experiments with elysia, including autoload, ran well and smoothly last week until i `bun update`d my project... then the project started segfaulting when running my code,  as well as your basic example.

I installed isolated, clean projects, with just your code, and came to conclude that your basic example:

* runs well with this package.json:
```
{
  "name": "8.10",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "@types/bun": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "elysia": "0.8.10",
    "elysia-autoload": "^0.1.5"
  }
}
```
* but crashes with that one:
```
{
  "name": "8.11",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "@types/bun": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "elysia": "0.8.11",
    "elysia-autoload": "^0.1.5"
  }
}
```

Latest elysia versions crash as well (up to latest 0.8.15)

I hope you can fix this...

**Comment by kravetsone** [comment]
@fredt34 
`elysia-autoload` doesn't work on >0.8.11 for me too( I don't know why

And Bun throw «`Segmentation fault`» for me when i test my plugin (my [Issue](https://github.com/oven-sh/bun/issues/8522)
It looks like I need time...

**Comment by fredt34** [comment]
Take your time, current versions are ok for me.

**Comment by daraHK88** [comment]
I tested your code without some other functionalities and this version is working on Elysia 0.8.14 and bun 1.0.25. I also made some modifications but maybe the problem is somewhere else. 


```
import { join, isAbsolute,resolve } from 'path'
import Elysia from 'elysia'

export interface ITypesOptions {
  output?: string | string[]
  typeName?: string
  useExport?: boolean
}

export interface IAutoloadOptions {
  pattern?: string
  dir?: string
  prefix?: string
}

export function getPath(dir: string) {
  return isAbsolute(dir) ? dir : resolve(join(process.argv[1], '..', dir));
}

export function sortByNestedParams(routes: string[]): string[] {
  return routes.sort((a, b) => getParamsCount(a) - getParamsCount(b));
}

function getParamsCount(path: string) {
  // Using a non-global regex and directly checking for the match
  const matches = path.match(/\[(.*?)\]/g);
  return matches ? matches.length : 0;
}

export function transformToUrl(path: string) {
  const replacements = [
    { regex: /\.(ts|tsx|js|jsx|mjs|cjs)$/u, replacement: '' },
    { regex: /\[\.\.\..*\]/gu, replacement: '*' },
    { regex: /\[(.*?)\]/gu, replacement: (match, group) => `:${group}` },
    { regex: /\]-\[/gu, replacement: '-:' },
    { regex: /\]\//gu, replacement: '/' },
    { regex: /\[|\]/gu, replacement: '' },
    { regex: /\/?index$/, replacement: '' },
  ];

  return replacements.reduce((url, { regex, replacement }) => url.replace(regex, replacement as string), path) || '/';
}


export async function autoload({ pattern, dir, prefix }: IAutoloadOptions = {}) {
  const directoryPath = getPath(dir || './routes')
  const app = new Elysia({
    name: 'elysia-autoload',
    seed: {
      pattern,
      dir,
      prefix,
    },
  })

  const glob = new Bun.Glob(pattern || '**/*.{ts,tsx,js,jsx,mjs,cjs}');
  const files = await Array.fromAsync(glob.scan({ cwd: directoryPath }));
  
  for await (const path of sortByNestedParams(files)) {
    const { default: file } = await import(join(directoryPath, path));
  
    if (!file) {
      throw new Error(`${path} doesn't provide export default`);
    }
  
    const url = transformToUrl(path);
    const groupOptions = {};
  
    app.group((prefix ?? '') + url, groupOptions, file);
  }
  
  return app
}
```
Then I imported in Elysia and works fine

**Comment by 7f8ddd** [comment]
Just clarifying that this is unrelated to the plugin. This is a bug in Bun itself, possibly due to recent Windows updates.

**Comment by daraHK88** [comment]
> Just clarifying that this is unrelated to the plugin. This is a bug in Bun itself, possibly due to recent Windows updates.

but the problem happened after I updated to the latest version of Elysia. downgrade the Elysia to version 0.8.10 and the plugin works fine

**Comment by 7f8ddd** [comment]
> > Just clarifying that this is unrelated to the plugin. This is a bug in Bun itself, possibly due to recent Windows updates.
> 
> but the problem happened after I updated to the latest version of Elysia. downgrade the Elysia to version 0.8.10 and the plugin works fine

Still a problem with Bun, not Elysia. Bun isn't supposed to ever crash, and if it does, that's a bug.

**Comment by fredt34** [comment]
I agree, the plugin just triggers a bug "somewhere else"...

**Comment by Bewinxed** [comment]
I'm running this on windows, and when autoloader is used with elysia version > 0.8.10 (Even with Elysia 1.0), It crashes and throws this error:

```
1 | /** The base Error type thrown for all TypeBox exceptions  */
2 | export class TypeBoxError extends Error {
3 |     constructor(message) {
4 |         super(message);
            ^
error: Duplicate type kind 'Files' detected
      at new TypeBoxError (/root/dev/elysiakit/node_modules/@sinclair/typebox/build/import/type/error/error.mjs:4:9)
      at new TypeSystemDuplicateTypeKind (/root/dev/elysiakit/node_modules/@sinclair/typebox/build/import/system/system.mjs:10:9)
      at Type (/root/dev/elysiakit/node_modules/@sinclair/typebox/build/import/system/system.mjs:27:19)
      at /root/dev/elysiakit/node_modules/elysia/dist/bun/index.js:4720:13
error: script "dev" exited with code 1
```
This is on **Ubuntu** not windows.

**Comment by kravetsone** [comment]
works fine for me on bun@1.0.30 & elysia@1.0.5 & elysia-autoload@0.1.9

**Comment by kravetsone** [comment]
> I'm running this on Ubuntu with bun --bun run dev, and when autoloader is used with elysia version > 0.8.10 (Even with Elysia 1.0), It crashes and throws this error:
> 
> ```
> 1 | /** The base Error type thrown for all TypeBox exceptions  */
> 2 | export class TypeBoxError extends Error {
> 3 |     constructor(message) {
> 4 |         super(message);
>             ^
> error: Duplicate type kind 'Files' detected
>       at new TypeBoxError (/root/dev/elysiakit/node_modules/@sinclair/typebox/build/import/type/error/error.mjs:4:9)
>       at new TypeSystemDuplicateTypeKind (/root/dev/elysiakit/node_modules/@sinclair/typebox/build/import/system/system.mjs:10:9)
>       at Type (/root/dev/elysiakit/node_modules/@sinclair/typebox/build/import/system/system.mjs:27:19)
>       at /root/dev/elysiakit/node_modules/elysia/dist/bun/index.js:4720:13
> error: script "dev" exited with code 1
> ```
> 
> This is on **Ubuntu** not windows.

Maybe it Elysia issue? https://github.com/elysiajs/elysia/issues/547
