### ISSUE TITLE
Websockets don't work at all

### ISSUE THREAD

**Issue by recanman** [kravetsone/elysia-autoload#10]
Try adding a websocket to a route. Doesn't work, it is ignored. Tested on `0.2.3` with various Elysia versions.

**Comment by kravetsone** [comment]
try to use [elysia-autoload@0.2.4](https://github.com/kravetsone/elysia-autoload/releases/tag/v0.2.4)

**Comment by recanman** [comment]
I upgraded and ran the same code again, got this error:
```
5912 |             return this._use(plugin2);
5913 |           if (typeof plugin2.default === "function")
5914 |             return plugin2.default(this);
5915 |           if (plugin2.default instanceof _Elysia)
5916 |             return this._use(plugin2.default);
5917 |           throw new Error(
                       ^
error: Invalid plugin type. Expected Elysia instance, function, or module with "default" as Elysia instance or function that returns Elysia instance.
      at /home/user/c/node_modules/elysia/dist/index.mjs:5917:17
```

**Comment by recanman** [comment]
I have a websocket in `index.ts`, like this:
```
const app = new Elysia()
//<all of my middlewares>
.ws() // websocket is right here
.listen() //...
```

**Comment by kravetsone** [comment]
> I upgraded and ran the same code again, got this error:
> ```typescript
> 5912 |             return this._use(plugin2);
> 5913 |           if (typeof plugin2.default === "function")
> 5914 |             return plugin2.default(this);
> 5915 |           if (plugin2.default instanceof _Elysia)
> 5916 |             return this._use(plugin2.default);
> 5917 |           throw new Error(
>                        ^
> error: Invalid plugin type. Expected Elysia instance, function, or module with "default" as Elysia instance or function that returns Elysia instance.
>       at /home/user/c/node_modules/elysia/dist/index.mjs:5917:17
> ```
> 
> `routes-types.ts` is still generated.

Which version of elysia u use? 1.0.23

Try to add await before autoload()

**Comment by recanman** [comment]
I am on the latest version. It works when adding `await` before autoload:
```typescript
	.use(
		await autoload({
			types: true,
		})
	)
```

**Comment by kravetsone** [comment]
> I am on the latest version. It works when adding `await` before autoload:
> ```typescript
> 	.use(
> 		await autoload({
> 			types: true,
> 		})
> 	)
> ```
> 
> I guess this can be considered fixed, but I would recommend adding the requirement for `await` in the README.

Yeah... I need to add article in README about lazy-load plugin
