### ISSUE TITLE
Generate route types with dynamic path

### ISSUE THREAD

**Issue by ThatOneCalculator** [kravetsone/elysia-autoload#12]
As seen in https://github.com/kravetsone/elysia-autoload/blob/main/example/routes.ts 
route types should be generated like

```ts
import type Route0 from "./routes/index";
import type Route1 from "./routes/test/[some]/index";
```

**Comment by kravetsone** [comment]
Improved in [elysia-autoload@1.0.1](https://github.com/kravetsone/elysia-autoload/releases/tag/v1.0.1)
