### ISSUE TITLE
Add support for "new Elysia" routes

### ISSUE THREAD

**Issue by deadlinecode** [kravetsone/elysia-autoload#15]
Currently routes only work when defining them like this
```ts
import type { ElysiaApp } from "app";

export default (app: ElysiaApp) => app.get("/", { hello: "world" });
```

Normally i often define my routes like this
```ts
import Elysia from "elysia";

export default new Elysia().get("/", { hello: "world" });
```

Which doesn't seem to work with autoload but it should.
Also this should work which does not
```ts
import Elysia from "elysia";

export default () => new Elysia().get("/", { hello: "world" });
```

The first one throws an error and the second one doesn't but the second one also doesn't handle anything i still get an 404 on "/"

**Comment by kravetsone** [comment]
> Currently routes only work when defining them like this
> 
> ```ts
> import type { ElysiaApp } from "app";
> 
> export default (app: ElysiaApp) => app.get("/", { hello: "world" });
> ```
> 
> Normally i often define my routes like this
> 
> ```ts
> import Elysia from "elysia";
> 
> export default new Elysia().get("/", { hello: "world" });
> ```
> 
> Which doesn't seem to work with autoload but it should. Also this should work which does not
> 
> ```ts
> import Elysia from "elysia";
> 
> export default () => new Elysia().get("/", { hello: "world" });
> ```
> 
> The first one throws an error and the second one doesn't but the second one also doesn't handle anything i still get an 404 on "/"

i can handle

```ts
import Elysia from "elysia";

export default new Elysia().get("/", { hello: "world" });
```

but idk how to support 

```ts
import Elysia from "elysia";

export default () => new Elysia().get("/", { hello: "world" });
```

only if i count arguments (better way) or add static analysis 

Do you need it?

**Comment by deadlinecode** [comment]
I mainly would need the first one

**Comment by kravetsone** [comment]
> I mainly would need the first one

All of them supported but new version isn't published

Do u want to help with type code-generation?

**Comment by deadlinecode** [comment]
Ima make a PR
