### ISSUE TITLE
Fix type support for eden

### ISSUE THREAD

**Issue by deadlinecode** [kravetsone/elysia-autoload#16]
Its great that the package already supports generating types for eden fetch.
However for eden treaty it doesn't quite work.
When i try to use the types for eden treaty i can't index my routes treaty-like but rather have to index the path
It also appends "index" at the end

```ts
import { treaty } from "@elysiajs/eden";

// APITypes is the generated type name
export const client = treaty<APITypes>("/");

// I have a route called /api/logout
// The types force me to once index treaty via ["/api/logoutindex"]
// And second it appends "index" at the end of each route because i define it as app.get("/")
client["/api/logoutindex"].get();
```

**Comment by deadlinecode** [comment]
This obviously doesn't work since eden treaty tries to call the wrong url

**Comment by deadlinecode** [comment]
In general it removes "/" from all routes that are not a file name
So if i have a file called "discord" in my "api" folder and i have a `app.get("/callback")` eden treaty shows me i need to use "/api/discordcallback"

As you can see the slash between discord and callback is missing

**Comment by deadlinecode** [comment]
Thats also why "index" is appended when i do `app.get("/")`

**Comment by deadlinecode** [comment]
Looks like eden fetch is also not working...
Also eden Fetch shows "//api/..." so it looks like it prepends a slash

**Comment by deadlinecode** [comment]
It looks like that when you are generating the types you are importing the handler functions aka the default exports of the routes
I think to get the elyisa type you would need to use `ElysiaWithBaseUrl<ReturnType<typeof route>>` but you are currently using `ElysiaWithBaseUrl<typeof route>`

**Comment by kravetsone** [comment]
> Its great that the package already supports generating types for eden fetch.
> However for eden treaty it doesn't quite work.
> When i try to use the types for eden treaty i can't index my routes treaty-like but rather have to index the path
> It also appends "index" at the end
> 
> ```ts
> import { treaty } from "@elysiajs/eden";
> 
> // APITypes is the generated type name
> export const client = treaty<APITypes>("/");
> 
> // I have a route called /api/logout
> // The types force me to once index treaty via ["/api/logoutindex"]
> // And second it appends "index" at the end of each route because i define it as app.get("/")
> client["/api/logoutindex"].get();
> ```

Not easy for me at the moment (no time for it)

Can you send a PR?

**Comment by deadlinecode** [comment]
Sure i will take a look at it and try to fix it
