### ISSUE TITLE
Feature Request: Support Multiple Files for the Same Endpoint

### ISSUE THREAD

**Issue by vastamaki** [kravetsone/elysia-autoload#21]
First off, thanks for the awesome work on this plugin!

I wanted to propose a feature that I believe would be really helpful, especially for those of us who prefer keeping each endpoint in a separate file. For example, it would be great to have something like:

- `/src/routes/events/post.ts`
- `/src/routes/events/get.ts`
Both of these would resolve to the same path: /api/v1/events. This would allow for better organization and scalability as the project grows.

I’m sure others could benefit from this flexibility too. Let me know if this is something you’d consider, or if there’s already a way to achieve this that I might have missed.

Thanks again for all your hard work! 🙌

**Comment by rtritto** [comment]
Any update?
This feature will be very useful.

**Comment by kravetsone** [comment]
Solved by adding solid-start inspired renaming index syntax! 

Ream more - https://docs.solidjs.com/solid-start/building-your-application/routing#renaming-index

![image](https://github.com/user-attachments/assets/485b079a-b989-449a-85e9-771b1b7f13bb)

Now you should do something like

-   /routes/events/(post).ts → /events
-   /routes/events/(get).ts → /events

**Comment by rtritto** [comment]
@kravetsone this plugin is generic (work only with Elysia) and isn't related to a specific web framework (like `vike` or `solid-start`).
This feature is needed because improves all routes with the `group` hook of Elysia.

**Comment by kravetsone** [comment]
> Solved by adding solid-start inspired renaming index syntax!

You didn't understand. I added (some).ts its inspired by solid-start

**Comment by rtritto** [comment]
Nvm, I misunderstood, in https://github.com/kravetsone/elysia-autoload/commit/0ddeb241c18883b950eb3672e81efe7af5fa2a0b you added:
```ts
    {
        regex: /\/?\((.*)\)/,
        replacement: "",
    },
```
Thanks!
