### ISSUE TITLE
[Node.js] Dynamic import of routes in Windows

### ISSUE THREAD

**Issue by rtritto** [kravetsone/elysia-autoload#24]
```console
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

### Related:
- https://github.com/kravetsone/elysia-autoload/pull/23#issuecomment-2386553083
- https://stackoverflow.com/questions/69665780/error-err-unsupported-esm-url-scheme-only-file-and-data-urls-are-supported-by/70057245#70057245

### Fix
https://github.com/kravetsone/elysia-autoload/blob/5920060b5ba819977b48e195fc526f4c331bb201/src/index.ts#L137

```diff
+ import { pathToFileURL } from 'node:url';
// ...
const fullPath = path.join(directoryPath, filePath);
- const file = await import(fullPath);
+ const file = await import(pathToFileURL(fullPath).href);  // import parameter is file:///C:/<FILEPATH>
```

### Alternative fixes
1) (hacky but performant)
  https://stackoverflow.com/questions/69665780/error-err-unsupported-esm-url-scheme-only-file-and-data-urls-are-supported-by/70057245#70057245
    ```diff
    const fullPath = path.join(directoryPath, filePath);
    - const file = await import(fullPath);
    + const file = await import(`file://${fullPath}`);  // import parameter is file://C:\<FILEPATH>
    ```
    OR
    ```diff
    + import path from 'node:path';
    // ...
    const fullPath = path.join(directoryPath, filePath);
    - const file = await import(fullPath);
    + const file = await import(`file://${path.resolve(directoryPath, file)}`);  // import parameter is file://C:\<FILEPATH>
    ```
    Similar usage with `@brillout/import`
    https://github.com/brillout/import/blob/ba848455442484eb258aaa2d9864d4848e4ed0fb/index.ts#L4-L34

**Comment by kravetsone** [comment]
fixed with https://github.com/kravetsone/elysia-autoload/pull/23
