### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by taro445** [kravetsone/elysia-autoload#25]
I encountered an issue when trying to use Elysia Validation in conjunction with **esbuild-plugin-autoload**.
This problem arises specifically during the bun build process.
Additionally, every request using Elysia Validation returns a 500 Internal server error.
This only happens with versions later than Elysia 1.1.6
````
app.post('/test', () => {
    return "Hello";
}, {
    body: t.Object({
        name: t.String()
    })
});
````
````
2 | var FC1=Object.create;var{getPrototypeOf:BC1,defineProperty:NV,getOwnPropertyNames:DC1}=Object;var YC1=Object.prototype.hasOwnProperty;var n1=(A,F,B)=>{B=A!=null?FC1(BC1(A)):{};const D=F||!A||!A.__esModule?NV(B,"default",{value:A,enumerable:!0}):B;for(let Y of DC1(A))if(!YC1.call(D,Y))NV(D,Y,{get:()=>A[Y],enumerable:!0});return D};var L=(A,F)=>()=>(F||A((F={exports:{}}).exports,F),F.exports);var p2=(A,F)=>{for(var B in F)NV(A,B,{get:F[B],enumerable:!0,configurable:!0,set:(D)=>F[B]=()=>D})};var $=(A,F)=>()=>(A&&(F=A(A=0)),F);function XQ(A){return A4(A)&&Symbol.asyncIterator in A}function UQ(A){return A4(A)&&Symbol.iterator in A}function K2(A){return A4(A)&&(Object.getPrototypeOf(A)===Object.prototype||Object.getPrototypeOf(A)===null)}function wQ(A){return A instanceof Promise}function J9(A){return A instanceof Date&&Number.isFinite(A.getTime())}function p9(A){return ArrayBuffer.isView(A)}function gD(A){return A instanceof globalThis.Uint8Array}function G0(A,F){return F in A}function A4(A){return A!==null&&type | ... truncated
TypeError: undefined is not an object (evaluating 'F.from[i]')
````

**Comment by kravetsone** [comment]
> Я столкнулся с той же проблемой, и чистая установка не помогла.
> 
> журнал ниже.
> 
> ```shell
> 1 | // @bun
> 2 | var H2=Object.create;var{getPrototypeOf:R2,defineProperty:f1,getOwnPropertyNames:b2}=Object;var x2=Object.prototype.hasOwnProperty;var k0=($,W,X)=>{X=$!=null?H2(R2($)):{};let Z=W||!$||!$.__esModule?f1(X,"default",{value:$,enumerable:!0}):X;for(let J of b2($))if(!x2.call(Z,J))f1(Z,J,{get:()=>$[J],enumerable:!0});return Z};var y1=($,W)=>()=>(W||$((W={exports:{}}).exports,W),W.exports);var z1=y1((e1)=>{Object.defineProperty(e1,"__esModule",{value:!0});e1.parse=F3;e1.serialize=z3;var G3=/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/,B3=/^("?)[\u0021\u0023-\u002B\u002D-\u003A\u003C-\u005B\u005D-\u007E]*\1$/,K3=/^([.]?[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)([.][a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*$/i,U3=/^[\u0020-\u003A\u003D-\u007E]*$/,w3=Object.prototype.toString,_3=(()=>{let $=function(){};return $.prototype=Object.create(null),$})();function F3($,W){let X=new _3,Z=$.length;if(Z<2)return X;let J=W?.decode||M3,j=0;do{let Y=$.indexOf("=",j);if(Y===-1)break;let G=$.indexOf(";",j),K=G===-1?Z:G;if(Y>K){j=$.lastIndexOf(";",Y-1)+1;contin | ... truncated
> 
> TypeError: undefined is not an object (evaluating 'W.from[Kind]')
>       at h (/root/project/node_modules/elysia/dist/bun/index.js:2:43154)
>       at A1 (/root/project/node_modules/elysia/dist/bun/index.js:2:43043)
>       at m (/root/project/node_modules/elysia/dist/bun/index.js:2:45718)
>       at add (/root/project/node_modules/elysia/dist/bun/index.js:520:8998)
>       at _use (/root/project/node_modules/elysia/dist/bun/index.js:520:23330)
>       at /root/project/node_modules/elysia/dist/bun/index.js:520:18852
> ```

 can u share build output? Possible bun build error
