### ISSUE TITLE
Use relative path to dynamic import

### ISSUE THREAD

**Issue by rtritto** [kravetsone/elysia-autoload#28]
```console
[vite] warning:
C:/test-elysia-autoload/node_modules/elysia-autoload/dist/index.js
102|    for await (const filePath of sortByNestedParams(files)) {
103|      const fullPath = path.join(directoryPath, filePath);
104|      const file = await import(fullPath);
   |                                ^^^^^^^^
105|      const importName = typeof getImportName === "string" ? getImportName : getImportName(file);
106|      if (!file[importName] && options?.skipImportErrors) continue;
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.

  Plugin: vite:import-analysis
  File: C:/test-elysia-autoload/node_modules/elysia-autoload/dist/index.js
```

### Fix
The ignore comment can be safely added.

https://github.com/kravetsone/elysia-autoload/blob/5920060b5ba819977b48e195fc526f4c331bb201/src/index.ts#L137

```diff
- const file = await import(fullPath);
+ const file = await import(/* @vite-ignore */ fullPath);
```

### Infos
vite@5.4.8

Maybe fix #24

**Comment by rtritto** [comment]
This error occurs only if `elysia-autoload` isn't transpiled

**Comment by kravetsone** [comment]
> This error occurs only if `elysia-autoload` isn't transpiled

Vite for browser shouldn't transpile elysia-autoload)

**Comment by rtritto** [comment]
So it's better to add `/* @vite-ignore */` anyway?

https://github.com/brillout/import/blob/ba848455442484eb258aaa2d9864d4848e4ed0fb/index.ts#L4-L34
Similar usage with `@brillout/import`: dynamic import + webpack use case with `/*webpackIgnore: true*/` (Idk why `/* @vite-ignore */` is missing if `@brillout/import` is used under vike (vite)

**Comment by rtritto** [comment]
The `vite:import-analysis` should ignore dependencies, so the `@vite-ignore` and `webpackIgnore` can be omitted.
