### ISSUE TITLE
Docker build failed.

### ISSUE THREAD

**Issue by bright-coder** [kravetsone/elysia-autoload#33]
# build.ts
import { autoload } from "esbuild-plugin-autoload"; // default import also supported

await Bun.build({
	entrypoints: ["./src/index.ts"],
	target: "bun",
	outdir: "out",
	plugins: [
		autoload({
			directory: "./src/routes",
		}),
	],
});

-----------------------

# Dockerfile

FROM oven/bun AS build

WORKDIR /app

COPY package.json package.json
COPY bun.lockb bun.lockb
COPY build.ts build.ts

RUN bun install

COPY ./src ./src

RUN bun build build.ts

RUN bun build --compile --minify-whitespace --minify-syntax --target bun --outfile server ./out/index.js

FROM gcr.io/distroless/base

COPY --from=build /app/server server

ENV NODE_ENV=production

CMD ["./server"]

EXPOSE 3000

-------------------
# Error log

[build 9/9] RUN bun build --compile --minify-whitespace --minify-syntax --target bun --outfile server ./out/index.js
FileNotFound opening root directory "./out

**Comment by kravetsone** [comment]
`bun build build.ts` is no action 
Use `bun run`

**Comment by bright-coder** [comment]
if i use bun run .Should i put command in package.json ?

can u give me example to build with Dockerfile.

thank you.

**Comment by bright-coder** [comment]
OK bro it's working. Thank you so much for fast response.

It's great plugin

**Comment by kravetsone** [comment]
> if i use bun run .Should i put command in package.json ?
> 
> can u give me example to build with Dockerfile.
> 
> thank you.

`build.ts` is just script 
U can run it with `bun build.ts` like u start u application
