### ISSUE TITLE
error: Cannot find package "elysia-autoload"

### ISSUE THREAD

**Issue by recanman** [kravetsone/elysia-autoload#6]
Bun version: `v1.0.33`
Elysia version: `1.0.10`
Autoload version: `0.2.1`

Everything is installed. I tried to downgrade but issues still persist.

When I run `bun run src/index.ts` with the code example in the README, I get this error:
```
error: Cannot find package "elysia-autoload"
```

It is in the `node_modules` folder. It's an odd error so I'm not sure what other information to provide.

**Comment by recanman** [comment]
Temporary solution: copy `node_modules/elysia-autoload/dist` to your source directory, then import it.

**Comment by kravetsone** [comment]
> Temporary solution: copy `node_modules/elysia-autoload/dist` to your source directory, then import it.

Sorry... I fix it earlier but forgot commit&publish it)

elysia-autoload@0.2.2 should fix
