### ISSUE TITLE
Build fails as of Bun 1.1.3 / 1.1.4

### ISSUE THREAD

**Issue by ThatOneCalculator** [kravetsone/elysia-autoload#7]
```sh
% bun run build       
$ bun build src/index.ts
3 | import { join as join2 } from "node:path";
             ^
error: No matching export in "node:path" for import "join"
    at /home/kainoa/redacted/node_modules/elysia-autoload/dist/index.js:3:10

7 | import { isAbsolute, join } from "node:path";
             ^
error: No matching export in "node:path" for import "isAbsolute"
    at /home/kainoa/redacted/node_modules/elysia-autoload/dist/index.js:7:10

7 | import { isAbsolute, join } from "node:path";
                         ^
error: No matching export in "node:path" for import "join"
    at /home/kainoa/redacted/node_modules/elysia-autoload/dist/index.js:7:22
error: script "build" exited with code 1
```

Code:
`src/index.ts`:
```ts
const app = new Elysia();
// ...
app.use(
	autoload({
		types: true,
	}),
);
```

Bun version: 1.1.4
Elysia version: 1.0.13
elysia-autoload version: 0.2.3

`bun run dev` still works fine.

**Comment by kravetsone** [comment]
> ```shell
> % bun run build       
> $ bun build src/index.ts
> 3 | import { join as join2 } from "node:path";
>              ^
> error: No matching export in "node:path" for import "join"
>     at /home/kainoa/redacted/node_modules/elysia-autoload/dist/index.js:3:10
> 
> 7 | import { isAbsolute, join } from "node:path";
>              ^
> error: No matching export in "node:path" for import "isAbsolute"
>     at /home/kainoa/redacted/node_modules/elysia-autoload/dist/index.js:7:10
> 
> 7 | import { isAbsolute, join } from "node:path";
>                          ^
> error: No matching export in "node:path" for import "join"
>     at /home/kainoa/redacted/node_modules/elysia-autoload/dist/index.js:7:22
> error: script "build" exited with code 1
> ```
> 
> Code: `src/index.ts`:
> 
> ```ts
> const app = new Elysia();
> // ...
> app.use(
> 	autoload({
> 		types: true,
> 	}),
> );
> ```
> 
> Bun version: 1.1.4 Elysia version: 1.0.13 elysia-autoload version: 0.2.3
> 
> `bun run dev` still works fine.

Bun issue - https://github.com/oven-sh/bun/issues/11321

**Comment by kravetsone** [comment]
> ```shell
> % bun run build       
> $ bun build src/index.ts
> 3 | import { join as join2 } from "node:path";
>              ^
> error: No matching export in "node:path" for import "join"
>     at /home/kainoa/redacted/node_modules/elysia-autoload/dist/index.js:3:10
> 
> 7 | import { isAbsolute, join } from "node:path";
>              ^
> error: No matching export in "node:path" for import "isAbsolute"
>     at /home/kainoa/redacted/node_modules/elysia-autoload/dist/index.js:7:10
> 
> 7 | import { isAbsolute, join } from "node:path";
>                          ^
> error: No matching export in "node:path" for import "join"
>     at /home/kainoa/redacted/node_modules/elysia-autoload/dist/index.js:7:22
> error: script "build" exited with code 1
> ```
> 
> Code: `src/index.ts`:
> 
> ```ts
> const app = new Elysia();
> // ...
> app.use(
> 	autoload({
> 		types: true,
> 	}),
> );
> ```
> 
> Bun version: 1.1.4 Elysia version: 1.0.13 elysia-autoload version: 0.2.3
> 
> `bun run dev` still works fine.

[I add support `Bun.build` by plugin](https://github.com/kravetsone/elysia-autoload?tab=readme-ov-file#bun-build-usage)
