### ISSUE TITLE
Doesn't seem to work with new Elysia or bun?

### ISSUE THREAD

**Issue by totaland** [kravetsone/elysia-autoload#8]
When I upgrade to latest Bun and Elysia and upgrade to the latest autoload it didn't work. Latest bun and Elysia work with older version 0.1.5. Maybe the group issue?

<img width="699" alt="image" src="https://github.com/kravetsone/elysia-autoload/assets/36496259/292059d4-98e9-49cc-b417-364addb252ac">

**Comment by kravetsone** [comment]
> When I upgrade to latest Bun and Elysia and upgrade to the latest autoload it didn't work. Latest bun and Elysia work with older version 0.1.5. Maybe the group issue?
> 
> <img alt="image" width="699" src="https://private-user-images.githubusercontent.com/36496259/328058731-292059d4-98e9-49cc-b417-364addb252ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDg5MzMsIm5iZiI6MTcxODQ0ODYzMywicGF0aCI6Ii8zNjQ5NjI1OS8zMjgwNTg3MzEtMjkyMDU5ZDQtOThlOS00OWNjLWI0MTctMzY0YWRkYjI1MmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDEwNTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYjNlZTE5ODYzMjA3YjZiZjA1YTg3ZWYxYTExMDUyNTcwZjMxZjc4NjU2NjhmYjE0MjViZDNiNDEyZjRjMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6u3H_hXWllTY70l8QN99PoHt1HdukKJmpKl7_WC8RKQ">

Sorry for the late response... try to use [elysia-autoload@0.2.4](https://github.com/kravetsone/elysia-autoload/releases/tag/v0.2.4)

**Comment by kravetsone** [comment]
Reopen it if you get this error for now
