### ISSUE TITLE
After "bun build src/index.ts --target bun --outfile src/index.js", The route lost

### ISSUE THREAD

**Issue by dwyanewang** [kravetsone/elysia-autoload#9]
This example is just based on `README.md`.
![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/bffcdf26-221a-415b-8090-c540ad5185d6)
![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/d1c24bdd-cd41-4766-baa7-4453af463fc9)
![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/77a22ded-71f6-4fe4-83ad-1fe9d4990d09)
`bun run --watch src/index.ts` The interface can be requested.
![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/2cee0f87-c7f5-4a42-8b31-8b0a103da934)
But `bun build src/index.ts --target bun --outfile src/index.js` and `bun run  src/index.js`
![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/ba3e3a56-bc29-422b-b506-1c0de45bc2d5)
 The interface cannot be requested.
![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/b53816a4-f0d1-43a7-abdc-46dab24f681f)

**Comment by kravetsone** [comment]
> This example is just based on `README.md`.
> ![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/bffcdf26-221a-415b-8090-c540ad5185d6)
> ![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/d1c24bdd-cd41-4766-baa7-4453af463fc9)
> ![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/77a22ded-71f6-4fe4-83ad-1fe9d4990d09)
> `bun run --watch src/index.ts` The interface can be requested.
> ![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/2cee0f87-c7f5-4a42-8b31-8b0a103da934)
> But `bun build src/index.ts --target bun --outfile src/index.js` and `bun run  src/index.js`
> ![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/ba3e3a56-bc29-422b-b506-1c0de45bc2d5)
>  The interface cannot be requested.
> ![image](https://github.com/kravetsone/elysia-autoload/assets/29390617/b53816a4-f0d1-43a7-abdc-46dab24f681f)
> 

Because autoload import files at runtime) You should not use `bun build` for this

**Comment by dwyanewang** [comment]
so the back-end projects don't need to be packaged?

**Comment by kravetsone** [comment]
> so the back-end projects don't need to be packaged?

It is better not to build plugins with autoload. Because they read files in runtime

**Comment by kravetsone** [comment]
> so the back-end projects don't need to be packaged?

[I add `Bun.build` support by plugin](https://github.com/kravetsone/elysia-autoload?tab=readme-ov-file#bun-build-usage)
